### ISSUE TITLE
put link to html version of book in README

### ISSUE THREAD

**Issue by kbuzzard** [leanprover-community/lean4-metaprogramming-book#64]
I know I'm an idiot who can't use the internet, but search for me stubbornly refuses to give me the URL of the web-based version of this book. I'm always being linked to the github. Can you please put a link in the README of the repo to the web URL? I would do it myself but I can't find it :-( Even just a link like they do with mathlib (in "About in top right of the github main page) would be great!

**Comment by arthurpaulino** [comment]
We don't have a html link yet. I'll talk to Sebastian and Leo about hosting the book like they do with the other Lean 4 books

**Comment by Seasawher** [comment]
What happens afterwards? I hope that a web version will be made available.
